#!/usr/bin/env bash

REMOTE=$1; shift
if [[ -z $REMOTE ]]; then
    REMOTE=jh1.xpcas.cc:40000
fi

$HOME/opt/ss/sslocal \
    -s $REMOTE \
    -b 127.0.0.1:4000 \
    -m chacha20-ietf-poly1305 -k HelloWorld. \
    $@
