#!/usr/bin/env bash

LocalAppData=$(cygpath --unix $LOCALAPPDATA)
if [[ ! -d "$LocalAppData" ]]; then
    echo "Failed to get \$LOCALAPPDATA"
    exit 1
fi

"$LocalAppData/Programs/Microsoft VS Code/bin/code" $@
