#!/usr/bin/env bash

HOST4=0.0.0.0
HOST6=::0
PORT=60000
METHOD=aes-256-gcm
PASS=HelloWorld.
TIMEOUT=60
DNS=1.1.1.1


MYDIR="$(cd "$(dirname "$0")"; pwd)"
pushd "$MYDIR"

./run \
        "$HOST4 -s $HOST6" \
        $PORT \
        $METHOD $PASS \
        $TIMEOUT \
        -d $DNS \
        --reuse-port \
        $@

popd
